services:
  db:
    image: postgres:15
    container_name: santa_postgres
    restart: always
    environment:
      POSTGRES_DB: santa_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"